"""Reboot watchdog installer: generates ki-resume.sh + LaunchAgent plist.

v0.3 A4: replaces the hardcoded ops/ templates (ops/ files remain only as
archived samples). All paths are derived from the running environment at
install time; re-running install regenerates both files.

launchctl is only ever invoked through run_launchctl() so tests can
monkeypatch it — unit tests must never touch the real launchd.
"""

from __future__ import annotations

import hashlib
import plistlib
import shutil
import stat
import subprocess
from pathlib import Path

from knowledge_ingest.config import AppConfig

START_INTERVAL_SECONDS = 900


def _home() -> Path:
    return Path.home()


def label_for(user: str | None = None) -> str:
    user = user or _home().name
    return f"com.{user}.ki-resume"


def script_path(config: AppConfig) -> Path:
    return config.pipeline_root / "bin" / "ki-resume.sh"


def plist_install_path(user: str | None = None) -> Path:
    return (_home() / "Library" / "LaunchAgents"
            / f"{label_for(user)}.plist")


def launchd_log_path(config: AppConfig) -> Path:
    return config.pipeline_root / "logs" / "launchd" / "ki-resume-launchd.log"


def run_launchctl(argv: list[str]) -> tuple[int, str, str]:
    """Adapter for launchctl; monkeypatched in tests."""
    proc = subprocess.run(argv, text=True, capture_output=True, check=False,
                          timeout=60)
    return proc.returncode, proc.stdout, proc.stderr


def is_loaded(user: str | None = None) -> bool:
    label = label_for(user)
    try:
        code, out, _err = run_launchctl(["launchctl", "list"])
    except (OSError, subprocess.TimeoutExpired):
        return False
    return code == 0 and label in out


def _resolve_ki() -> str:
    return shutil.which("knowledge-ingest") or "knowledge-ingest"


def _repo_root() -> Path:
    import knowledge_ingest

    return Path(knowledge_ingest.__file__).resolve().parents[2]


def generate_script(config: AppConfig, ki_path: str, repo_root: Path,
                    config_path: Path) -> str:
    log_root = config.pipeline_root / "jobs"
    return f"""\
#!/bin/zsh
# knowledge-ingest reboot watchdog — generated by `knowledge-ingest watchdog install`.
# Regenerated on every install; manual edits will be overwritten.
# Idempotent: resume --exec skips jobs whose preprocess lock is alive.
export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"
KI="{ki_path}"
REPO="{repo_root}"
CONFIG="{config_path}"
LOG_ROOT="{log_root}"
LOG="$LOG_ROOT/ki-resume.log"

mkdir -p "$(dirname "$LOG")" 2>/dev/null || LOG="/tmp/ki-resume.log"

# wait for the repo volume to mount (up to 10 minutes)
mounted=0
for i in {{1..60}}; do
  [ -d "$REPO" ] && {{ mounted=1; break; }}
  sleep 10
done
if [ "$mounted" = "0" ]; then
  echo "$(date '+%F %T') repo volume not mounted, skipping round" >> "$LOG"
  exit 1
fi

"$KI" resume --exec --config "$CONFIG" >> "$LOG" 2>&1
rc=$?
echo "$(date '+%F %T') resume --exec exit=$rc" >> "$LOG"
exit $rc
"""


def generate_plist_bytes(config: AppConfig, script: Path) -> bytes:
    cfg = {
        "Label": label_for(),
        "ProgramArguments": ["/bin/zsh", str(script)],
        "RunAtLoad": True,
        "StartInterval": START_INTERVAL_SECONDS,
        "StandardOutPath": str(launchd_log_path(config)),
        "StandardErrorPath": str(launchd_log_path(config)),
    }
    return plistlib.dumps(cfg, fmt=plistlib.FMT_XML)


def _sha(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()[:16]


def install(config: AppConfig) -> int:
    script = script_path(config)
    plist_dst = plist_install_path()
    script.parent.mkdir(parents=True, exist_ok=True)
    launchd_log_path(config).parent.mkdir(parents=True, exist_ok=True)
    repo = _repo_root()
    content = generate_script(
        config, _resolve_ki(), repo, repo / "config.example.yaml")
    plist_data = generate_plist_bytes(config, script)

    old_script = script.read_text(encoding="utf-8") if script.exists() else None
    old_plist = plist_dst.read_bytes() if plist_dst.exists() else None
    if (old_script == content and old_plist == plist_data and is_loaded()):
        print(f"watchdog: already up to date ({plist_dst})")
        return 0

    script.write_text(content, encoding="utf-8")
    script.chmod(script.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP
                 | stat.S_IXOTH)
    if old_script is not None and old_script != content:
        print(f"watchdog: script updated ({_sha(old_script.encode())} -> "
              f"{_sha(content.encode())})")
    if old_plist is not None and old_plist != plist_data:
        print(f"watchdog: plist updated ({_sha(old_plist)} -> {_sha(plist_data)})")

    loaded = is_loaded()
    if loaded:
        run_launchctl(["launchctl", "unload", str(plist_dst)])
    plist_dst.parent.mkdir(parents=True, exist_ok=True)
    plist_dst.write_bytes(plist_data)
    code, out, err = run_launchctl(["launchctl", "load", str(plist_dst)])
    if code != 0:
        print(f"watchdog: launchctl load failed: {(err or out).strip()}")
        return 1
    print(f"watchdog: installed ({script})")
    print(f"watchdog: loaded ({plist_dst})")
    return 0


def status(config: AppConfig) -> int:
    script = script_path(config)
    plist_dst = plist_install_path()
    installed = script.exists() and plist_dst.exists()
    if not installed:
        print("watchdog: not installed "
              "(run `knowledge-ingest watchdog install`)")
        return 0
    loaded = is_loaded()
    state = "loaded" if loaded else "NOT loaded (launchctl list miss)"
    print(f"watchdog: installed, {state}")
    print(f"watchdog: script  {script} "
          f"(sha256:{_sha(script.read_bytes())})")
    print(f"watchdog: plist   {plist_dst} "
          f"(sha256:{_sha(plist_dst.read_bytes())})")
    return 0


def uninstall(config: AppConfig) -> int:
    plist_dst = plist_install_path()
    script = script_path(config)
    if not plist_dst.exists() and not script.exists():
        print("watchdog: not installed")
        return 0
    if plist_dst.exists() and is_loaded():
        run_launchctl(["launchctl", "unload", str(plist_dst)])
    if plist_dst.exists():
        plist_dst.unlink()
    if script.exists():
        script.unlink()
    print("watchdog: uninstalled (logs kept under "
          f"{launchd_log_path(config).parent})")
    return 0
